### PR TITLE
clears null and removes undefined query parameter

### PR DESCRIPTION
**Pull request by rafaltrojanowski**

### CODE REVIEW

**Comment by amiel** [comment]
@rafaltrojanowski can you give a little more context for your use case here?

I think it might make sense for us to delete a query parameter if it is `undefined`, but I'm a little worried about deleting the case where it is `null`, as I could also see a use-case where this property would be needed.

**Comment by rafaltrojanowski** [comment]
Hi @amiel 

I reproduced my use case here:
https://github.com/rafaltrojanowski/notes/pull/1/files

You can simply run 'ember tests' on this branch, console logs should give you whole context.

In fact backend recieves "null" for category as params are stringified. Correct me if I'm wrong.

Thanks!

**Comment by amiel** [comment]
@rafaltrojanowski I'll check it out.

**Comment by amiel** [comment]
@rafaltrojanowski thanks for the example app.

What are your thoughts on including a query param for `null` values, but with an empty string.

For example:

```javascript
this.store.query('note', { category: null, filter: undefined, tag: 'foo' })
// => /api/notes?category=&tag=foo
```

I don't feel too strongly about that, but wanted to see if that makes any sense to you, as it would be nice to keep the property around for null values. For a little context, one reason I'm thinking this way is that it is consistent with how JSON is serialized:

```javascript
JSON.stringify({ foo: undefined, bar: null })
// => "{"bar":null}"
```

Either way, I like the feature but do have one request. I'll use the brand new Github review feature :)

**Comment by rafaltrojanowski** [comment]
@amiel 

Answering your question:

When a controller's query param property is currently set to its default value, this value won't be serialized into the URL. So in the above example, if page is 1, the URL might look like /articles, but once someone sets the controller's page value to 2, the URL will become /articles?page=2

Source: https://guides.emberjs.com/v2.3.0/routing/query-params/#toc_default-values-and-deserialization

Anyway, I found cases when I had url like  `/articles?page=`, so probably I've did it wrongly (maybe forgot to define default value in controller).

**Comment by rafaltrojanowski** [comment]
@amiel Maybe that makes sense, I was guided by https://guides.emberjs.com/v2.3.0/routing/query-params/#toc_default-values-and-deserialization. Feel free to update PR.

**Comment by rafaltrojanowski** [comment]
@amiel I've updated PR, could you review please?

**Comment by rafaltrojanowski** [comment]
@amiel Thanks for preparing tests 😄 Happy to merge?

**Comment by rafaltrojanowski** [comment]
Thanks for merging @amiel.

BTW I'm stil thinking if ```Ember.copy()``` is good there.
Maybe it would be better build new query on the fly like:

```
var newQuery = {};

if (query !== undefined) {
  Object.keys(query).forEach(function(key) {
    if (query[key] === null ) {
      newQuery[key] = "";
    } else if (query[key] === undefined) {
    } else {
      newQuery[key] = query[key];
    }
  });
}

```

Clarity, maintainability or performance? :) I'm courious your opinion. Big up!

**Comment by amiel** [comment]
@rafaltrojanowski I like this approach. I don't have a strong opinion about it being better or worse.

They are both clear to me (although this one is slightly more verbose). I feel like this one might be more performant as the copy and filtering happen in one step, but I think the difference would be negligible and not worth fretting over without a benchmark.

Those are my thoughts. It's always fun to try coding something a few ways and critiquing which seems better. I'm happy with either approach for this project.

**Pull request merged**
