### PR TITLE
Fix bug (Array params have indexes) and upgrade ember-cli

### PR DESCRIPTION
**Pull request by samdemaeyer**
In order to fix issue https://github.com/amiel/ember-data-url-templates/issues/47, I think it is wise to upgrade `ember-cli` and sorts.

The actual issue was related to a hack in the code base. With upgrading, that hack as not needed anymore and [removing it](https://github.com/amiel/ember-data-url-templates/pull/48/commits/ac58ec86b0137e5fa2684e6692c34d95c4647427) fixed the problem.

### CODE REVIEW

**Comment by amiel** [comment]
Hi @samdemaeyer. Thanks so much for contributing and sorry for the delay in getting back to you.

I super appreciate you going through the work to upgrade Ember. If you put that in a PR on its own, I will definitely merge it.

I'd like to dig in a little more on the removal of `sortQueryParams`. Your comment states that we don't need the hack anymore. I don't have any apps using ember-data 3.0, so I may be behind on my knowledge, but it seems to me that the sortQueryParams hack is still needed to prevent https://github.com/amiel/ember-data-url-templates/issues/19.

I'm not sure that there is a test that verifies the solution of #19, so I'll write one.

**Comment by samdemaeyer** [comment]
@amiel, the reason I removed the hack is that this has been merged => https://github.com/emberjs/data/pull/3099
But feel free to do some testing around it. In the mean time, I have created a new branch for the [ember-upgrade](https://github.com/amiel/ember-data-url-templates/pull/50) (https://github.com/amiel/ember-data-url-templates/pull/50)
Please leave this pr open as I am using this fork/commit in my package.json to fix our current apps.

**Comment by amiel** [comment]
@samdemaeyer Thanks!!! I will check out #50.

**Comment by amiel** [comment]
Regarding emberjs/data#3099, it was [actually removed](https://github.com/emberjs/rfcs/pull/171#issuecomment-400749267) [in ember-data 2.10](https://emberjs.com/blog/2016/11/30/ember-2-10-released.html#toc_move-code-ds-improved-ajax-code-out-of-code-beta-code-channel).

I totally understand how you got there, though. [This comment](https://github.com/amiel/ember-data-url-templates/blob/f85febc91c9aaf29200fc97d4bb675b02cb91c61/addon/mixins/url-templates.js#L60-L63) is not very clear on what would allow the hack to be removed.

**Comment by amiel** [comment]
@samdemaeyer I've updated my comment to prevent similar confusion and added a test that verifies the need for that hack (see #51).

Sorry about the confusion my stale comments may have caused.

The good news is that you found a workaround. You should be able to define `sortQueryParams` in your adapter. Try something like this:

```js
sortQueryParams(params) {
  return params;
}
```

Or copy the implementation of [`sortQueryParams` from ember-data](https://github.com/emberjs/data/blob/099d066eab8985f76aa6656aaba797fb184e7d8b/addon/adapters/rest.js#L343-L356). I know this isn't ideal, but hopefully this workaround allows you to continue doing what you need to do until we can find a better fix for #47.

**Comment by samdemaeyer** [comment]
Thanks, @amiel! It's not ideal, but it works. Thanks for the quick responses! Closing this PR.

**Pull request closed without merging**
